name: farkle_simulator
version: 0.0.1
description: >-
  Simulates rounds of the game Farkle.
author: Jerold Albertson <jerold.albertson@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'
dev_dependencies:
  test: any