name: farkle_simulator
version: 0.0.1
description: Simulates rounds of Farkle.
#author: Jerold Albertson <jerold.albertson@gmail.com>
#homepage: https://jerold.github.io/FarkleSimulator

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  intl: any
  wui_builder: any
  redux: any
  pwa: any

dev_dependencies:
  build_runner: any
  build_test: any
  build_web_compilers: any
  test: any
